In [21]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('odi_df.csv')
df.head()

,Team1,Team2,Winner,Margin,Ground,Date,ScoreID
0,England,South Africa,England,104 runs,The Oval,"May 30, 2019",ODI # 4143
1,Pakistan,West Indies,West Indies,7 wickets,Nottingham,"May 31, 2019",ODI # 4144
2,New Zealand,Sri Lanka,New Zealand,10 wickets,Cardiff,"Jun 1, 2019",ODI # 4145
3,Afghanistan,Australia,Australia,7 wickets,Bristol,"Jun 1, 2019",ODI # 4146
4,Bangladesh,South Africa,Bangladesh,21 runs,The Oval,"Jun 2, 2019",ODI # 4147

In [3]:
df.shape

(45, 7)

In [106]:
score_map={}

for ind,row in df.iterrows():
    a=row['Team1']+' vs '+row['Team2']
    b=row['Team2']+' vs '+row['Team1']
    
    score_map[a]=row['ScoreID']
    score_map[b]=row['ScoreID']

score_map

{'England vs South Africa': 'ODI # 4143',
 'South Africa vs England': 'ODI # 4143',
 'Pakistan vs West Indies': 'ODI # 4144',
 'West Indies vs Pakistan': 'ODI # 4144',
 'New Zealand vs Sri Lanka': 'ODI # 4145',
 'Sri Lanka vs New Zealand': 'ODI # 4145',
 'Afghanistan vs Australia': 'ODI # 4146',
 'Australia vs Afghanistan': 'ODI # 4146',
 'Bangladesh vs South Africa': 'ODI # 4147',
 'South Africa vs Bangladesh': 'ODI # 4147',
 'England vs Pakistan': 'ODI # 4148',
 'Pakistan vs England': 'ODI # 4148',
 'Afghanistan vs Sri Lanka': 'ODI # 4149',
 'Sri Lanka vs Afghanistan': 'ODI # 4149',
 'India vs South Africa': 'ODI # 4150',
 'South Africa vs India': 'ODI # 4150',
 'Bangladesh vs New Zealand': 'ODI # 4151',
 'New Zealand vs Bangladesh': 'ODI # 4151',
 'Australia vs West Indies': 'ODI # 4152',
 'West Indies vs Australia': 'ODI # 4152',
 'England vs Bangladesh': 'ODI # 4153',
 'Bangladesh vs England': 'ODI # 4153',
 'Afghanistan vs New Zealand': 'ODI # 4154',
 'New Zealand vs Afghanistan': 'ODI # 4154',
 'Australia vs India': 'ODI # 4155',
 'India vs Australia': 'ODI # 4155',
 'South Africa vs West Indies': 'ODI # 4156',
 'West Indies vs South Africa': 'ODI # 4156',
 'Australia vs Pakistan': 'ODI # 4157',
 'Pakistan vs Australia': 'ODI # 4157',
 'England vs West Indies': 'ODI # 4158',
 'West Indies vs England': 'ODI # 4158',
 'Australia vs Sri Lanka': 'ODI # 4159',
 'Sri Lanka vs Australia': 'ODI # 4159',
 'Afghanistan vs South Africa': 'ODI # 4160',
 'South Africa vs Afghanistan': 'ODI # 4160',
 'India vs Pakistan': 'ODI # 4161',
 'Pakistan vs India': 'ODI # 4161',
 'Bangladesh vs West Indies': 'ODI # 4162',
 'West Indies vs Bangladesh': 'ODI # 4162',
 'England vs Afghanistan': 'ODI # 4163',
 'Afghanistan vs England': 'ODI # 4163',
 'New Zealand vs South Africa': 'ODI # 4165',
 'South Africa vs New Zealand': 'ODI # 4165',
 'Australia vs Bangladesh': 'ODI # 4166',
 'Bangladesh vs Australia': 'ODI # 4166',
 'England vs Sri Lanka': 'ODI # 4168',
 'Sri Lanka vs England': 'ODI # 4168',
 'Afghanistan vs India': 'ODI # 4169',
 'India vs Afghanistan': 'ODI # 4169',
 'New Zealand vs West Indies': 'ODI # 4170',
 'West Indies vs New Zealand': 'ODI # 4170',
 'Pakistan vs South Africa': 'ODI # 4171',
 'South Africa vs Pakistan': 'ODI # 4171',
 'Afghanistan vs Bangladesh': 'ODI # 4172',
 'Bangladesh vs Afghanistan': 'ODI # 4172',
 'England vs Australia': 'ODI # 4191',
 'Australia vs England': 'ODI # 4191',
 'New Zealand vs Pakistan': 'ODI # 4174',
 'Pakistan vs New Zealand': 'ODI # 4174',
 'India vs West Indies': 'ODI # 4175',
 'West Indies vs India': 'ODI # 4175',
 'South Africa vs Sri Lanka': 'ODI # 4176',
 'Sri Lanka vs South Africa': 'ODI # 4176',
 'Afghanistan vs Pakistan': 'ODI # 4177',
 'Pakistan vs Afghanistan': 'ODI # 4177',
 'Australia vs New Zealand': 'ODI # 4178',
 'New Zealand vs Australia': 'ODI # 4178',
 'England vs India': 'ODI # 4179',
 'India vs England': 'ODI # 4179',
 'Sri Lanka vs West Indies': 'ODI # 4180',
 'West Indies vs Sri Lanka': 'ODI # 4180',
 'Bangladesh vs India': 'ODI # 4182',
 'India vs Bangladesh': 'ODI # 4182',
 'England vs New Zealand': 'ODI # 4192',
 'New Zealand vs England': 'ODI # 4192',
 'Afghanistan vs West Indies': 'ODI # 4184',
 'West Indies vs Afghanistan': 'ODI # 4184',
 'Bangladesh vs Pakistan': 'ODI # 4186',
 'Pakistan vs Bangladesh': 'ODI # 4186',
 'India vs Sri Lanka': 'ODI # 4187',
 'Sri Lanka vs India': 'ODI # 4187',
 'Australia vs South Africa': 'ODI # 4188',
 'South Africa vs Australia': 'ODI # 4188',
 'India vs New Zealand': 'ODI # 4190',
 'New Zealand vs India': 'ODI # 4190'}

Extracting batting Data to csv

In [88]:
df_1=pd.read_csv('odi_bat_summary.csv')
df_1.head(10)

,Match,Team_Innings,Batting_Pos,Batsman,Dismissal,Runs,Balls,4s,6s,SR
0,England vs South Africa,England,1,Jason Roy,c du Plessis b Phehlukwayo,54,53,8,0,101.88
1,England vs South Africa,England,2,Jonny Bairstow,c †de Kock b Imran Tahir,0,1,0,0,0
2,England vs South Africa,England,3,Joe Root,c Duminy b Rabada,51,59,5,0,86.44
3,England vs South Africa,England,4,Eoin Morgan (c),c Markram b Imran Tahir,57,60,4,3,95
4,England vs South Africa,England,5,Ben Stokes,c Amla b Ngidi,89,79,9,0,112.65
5,England vs South Africa,England,6,Jos Buttler †,b Ngidi,18,16,0,0,112.5
6,England vs South Africa,England,7,Moeen Ali,c du Plessis b Ngidi,3,9,0,0,33.33
7,England vs South Africa,England,8,Chris Woakes,c du Plessis b Rabada,13,14,1,0,92.85
8,England vs South Africa,England,9,Liam Plunkett,NaN,9,6,1,0,150
9,England vs South Africa,England,10,Jofra Archer,NaN,7,3,1,0,233.33

In [89]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 808 entries, 0 to 807
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Match         808 non-null    object
 1   Team_Innings  808 non-null    object
 2   Batting_Pos   808 non-null    int64
 3   Batsman       808 non-null    object
 4   Dismissal     671 non-null    object
 5   Runs          808 non-null    int64
 6   Balls         808 non-null    int64
 7   4s            808 non-null    int64
 8   6s            808 non-null    int64
 9   SR            808 non-null    object
dtypes: int64(5), object(5)
memory usage: 63.2+ KB

In [90]:
df_1.shape
df_1['Dismissal'].isnull().head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9     True
Name: Dismissal, dtype: bool

In [91]:
df_1['out']=df_1.Dismissal.apply(lambda x: "0" if x is None else "1")
df_1.head(20)

,Match,Team_Innings,Batting_Pos,Batsman,Dismissal,Runs,Balls,4s,6s,SR,out
0,England vs South Africa,England,1,Jason Roy,c du Plessis b Phehlukwayo,54,53,8,0,101.88,1
1,England vs South Africa,England,2,Jonny Bairstow,c †de Kock b Imran Tahir,0,1,0,0,0,1
2,England vs South Africa,England,3,Joe Root,c Duminy b Rabada,51,59,5,0,86.44,1
3,England vs South Africa,England,4,Eoin Morgan (c),c Markram b Imran Tahir,57,60,4,3,95,1
4,England vs South Africa,England,5,Ben Stokes,c Amla b Ngidi,89,79,9,0,112.65,1
5,England vs South Africa,England,6,Jos Buttler †,b Ngidi,18,16,0,0,112.5,1
6,England vs South Africa,England,7,Moeen Ali,c du Plessis b Ngidi,3,9,0,0,33.33,1
7,England vs South Africa,England,8,Chris Woakes,c du Plessis b Rabada,13,14,1,0,92.85,1
8,England vs South Africa,England,9,Liam Plunkett,NaN,9,6,1,0,150,1
9,England vs South Africa,England,10,Jofra Archer,NaN,7,3,1,0,233.33,1
10,England vs South Africa,South Africa,1,Quinton de Kock †,c Root b Plunkett,68,74,6,2,91.89,1
11,England vs South Africa,South Africa,2,Hashim Amla,c †Buttler b Plunkett,13,23,1,0,56.52,1
12,England vs South Africa,South Africa,3,Aiden Markram,c Root b Archer,11,12,2,0,91.66,1
13,England vs South Africa,South Africa,4,Faf du Plessis (c),c Ali b Archer,5,7,1,0,71.42,1
14,England vs South Africa,South Africa,5,Rassie van der Dussen,c Ali b Archer,50,61,4,1,81.96,1
15,England vs South Africa,South Africa,6,Jean-Paul Duminy,c Stokes b Ali,8,11,1,0,72.72,1
16,England vs South Africa,South Africa,7,Dwaine Pretorius,run out (Stokes/Morgan),1,1,0,0,100,1
17,England vs South Africa,South Africa,8,Andile Phehlukwayo,c Stokes b Rashid,24,25,4,0,96,1
18,England vs South Africa,South Africa,9,Kagiso Rabada,c Plunkett b Stokes,11,19,2,0,57.89,1
19,England vs South Africa,South Africa,10,Lungi Ngidi,NaN,6,5,0,1,120,1

In [96]:
df_1.loc[df_1['Dismissal'].isnull(),'out']=0
df_1.head(20)

,Match,Team_Innings,Batting_Pos,Batsman,Dismissal,Runs,Balls,4s,6s,SR,out
0,England vs South Africa,England,1,Jason Roy,c du Plessis b Phehlukwayo,54,53,8,0,101.88,1
1,England vs South Africa,England,2,Jonny Bairstow,c †de Kock b Imran Tahir,0,1,0,0,0,1
2,England vs South Africa,England,3,Joe Root,c Duminy b Rabada,51,59,5,0,86.44,1
3,England vs South Africa,England,4,Eoin Morgan (c),c Markram b Imran Tahir,57,60,4,3,95,1
4,England vs South Africa,England,5,Ben Stokes,c Amla b Ngidi,89,79,9,0,112.65,1
5,England vs South Africa,England,6,Jos Buttler †,b Ngidi,18,16,0,0,112.5,1
6,England vs South Africa,England,7,Moeen Ali,c du Plessis b Ngidi,3,9,0,0,33.33,1
7,England vs South Africa,England,8,Chris Woakes,c du Plessis b Rabada,13,14,1,0,92.85,1
8,England vs South Africa,England,9,Liam Plunkett,NaN,9,6,1,0,150,0
9,England vs South Africa,England,10,Jofra Archer,NaN,7,3,1,0,233.33,0
10,England vs South Africa,South Africa,1,Quinton de Kock †,c Root b Plunkett,68,74,6,2,91.89,1
11,England vs South Africa,South Africa,2,Hashim Amla,c †Buttler b Plunkett,13,23,1,0,56.52,1
12,England vs South Africa,South Africa,3,Aiden Markram,c Root b Archer,11,12,2,0,91.66,1
13,England vs South Africa,South Africa,4,Faf du Plessis (c),c Ali b Archer,5,7,1,0,71.42,1
14,England vs South Africa,South Africa,5,Rassie van der Dussen,c Ali b Archer,50,61,4,1,81.96,1
15,England vs South Africa,South Africa,6,Jean-Paul Duminy,c Stokes b Ali,8,11,1,0,72.72,1
16,England vs South Africa,South Africa,7,Dwaine Pretorius,run out (Stokes/Morgan),1,1,0,0,100,1
17,England vs South Africa,South Africa,8,Andile Phehlukwayo,c Stokes b Rashid,24,25,4,0,96,1
18,England vs South Africa,South Africa,9,Kagiso Rabada,c Plunkett b Stokes,11,19,2,0,57.89,1
19,England vs South Africa,South Africa,10,Lungi Ngidi,NaN,6,5,0,1,120,0

In [97]:
df_1.drop(columns=["Dismissal"],inplace=True)

In [100]:
df_1.tail(20)

,Match,Team_Innings,Batting_Pos,Batsman,Runs,Balls,4s,6s,SR,out
788,New Zealand vs England,New Zealand,2,Henry Nicholls,55,77,4,0,71.42,1
789,New Zealand vs England,New Zealand,3,Kane Williamson (c),30,53,2,0,56.6,1
790,New Zealand vs England,New Zealand,4,Ross Taylor,15,31,0,0,48.38,1
791,New Zealand vs England,New Zealand,5,Tom Latham †,47,56,2,1,83.92,1
792,New Zealand vs England,New Zealand,6,James Neesham,19,25,3,0,76,1
793,New Zealand vs England,New Zealand,7,Colin de Grandhomme,16,28,0,0,57.14,1
794,New Zealand vs England,New Zealand,8,Mitchell Santner,5,9,0,0,55.55,0
795,New Zealand vs England,New Zealand,9,Matt Henry,4,2,1,0,200,1
796,New Zealand vs England,New Zealand,10,Trent Boult,1,2,0,0,50,0
797,New Zealand vs England,England,1,Jason Roy,17,20,3,0,85,1
798,New Zealand vs England,England,2,Jonny Bairstow,36,55,7,0,65.45,1
799,New Zealand vs England,England,3,Joe Root,7,30,0,0,23.33,1
800,New Zealand vs England,England,4,Eoin Morgan (c),9,22,0,0,40.9,1
801,New Zealand vs England,England,5,Ben Stokes,84,98,5,2,85.71,0
802,New Zealand vs England,England,6,Jos Buttler †,59,60,6,0,98.33,1
803,New Zealand vs England,England,7,Chris Woakes,2,4,0,0,50,1
804,New Zealand vs England,England,8,Liam Plunkett,10,10,1,0,100,1
805,New Zealand vs England,England,9,Jofra Archer,0,1,0,0,0,1
806,New Zealand vs England,England,10,Adil Rashid,0,0,0,0,-,1
807,New Zealand vs England,England,11,Mark Wood,0,0,0,0,-,1

Removing special characters from batsman name

In [103]:
df_1['Batsman']=df_1['Batsman'].apply(lambda x: x.replace('(c)',''))
df_1['Batsman']=df_1['Batsman'].apply(lambda x: x.replace('†',''))
df_1.head(10)

,Match,Team_Innings,Batting_Pos,Batsman,Runs,Balls,4s,6s,SR,out
0,England vs South Africa,England,1,Jason Roy,54,53,8,0,101.88,1
1,England vs South Africa,England,2,Jonny Bairstow,0,1,0,0,0,1
2,England vs South Africa,England,3,Joe Root,51,59,5,0,86.44,1
3,England vs South Africa,England,4,Eoin Morgan,57,60,4,3,95,1
4,England vs South Africa,England,5,Ben Stokes,89,79,9,0,112.65,1
5,England vs South Africa,England,6,Jos Buttler,18,16,0,0,112.5,1
6,England vs South Africa,England,7,Moeen Ali,3,9,0,0,33.33,1
7,England vs South Africa,England,8,Chris Woakes,13,14,1,0,92.85,1
8,England vs South Africa,England,9,Liam Plunkett,9,6,1,0,150,0
9,England vs South Africa,England,10,Jofra Archer,7,3,1,0,233.33,0

In [108]:
df_1['ScoreID']=df_1['Match'].map(score_map)
df_1.tail(10)

,Match,Team_Innings,Batting_Pos,Batsman,Runs,Balls,4s,6s,SR,out,ScoreID
798,New Zealand vs England,England,2,Jonny Bairstow,36,55,7,0,65.45,1,ODI # 4192
799,New Zealand vs England,England,3,Joe Root,7,30,0,0,23.33,1,ODI # 4192
800,New Zealand vs England,England,4,Eoin Morgan,9,22,0,0,40.9,1,ODI # 4192
801,New Zealand vs England,England,5,Ben Stokes,84,98,5,2,85.71,0,ODI # 4192
802,New Zealand vs England,England,6,Jos Buttler,59,60,6,0,98.33,1,ODI # 4192
803,New Zealand vs England,England,7,Chris Woakes,2,4,0,0,50,1,ODI # 4192
804,New Zealand vs England,England,8,Liam Plunkett,10,10,1,0,100,1,ODI # 4192
805,New Zealand vs England,England,9,Jofra Archer,0,1,0,0,0,1,ODI # 4192
806,New Zealand vs England,England,10,Adil Rashid,0,0,0,0,-,1,ODI # 4192
807,New Zealand vs England,England,11,Mark Wood,0,0,0,0,-,1,ODI # 4192

In [109]:
df_2=pd.read_csv('odi_bowl_fact_summary.csv')
df_2.head()

,BOWLING,O,M,R,W,ECON,0s,4s,6s,WD,NB,Bowling_Team,Match
0,Imran Tahir,10.0,0,61,2,6.1,20,4,0,0,0,South Africa,England vs South Africa
1,Lungi Ngidi,10.0,0,66,3,6.6,28,6,2,2,0,South Africa,England vs South Africa
2,Kagiso Rabada,10.0,0,66,2,6.6,24,8,0,2,0,South Africa,England vs South Africa
3,Dwaine Pretorius,7.0,0,42,0,6.0,17,5,0,0,0,South Africa,England vs South Africa
4,Andile Phehlukwayo,8.0,0,44,1,5.5,23,4,0,4,0,South Africa,England vs South Africa

In [111]:
df_2['ScoreID']=df_2['Match'].map(score_map)
df_2.tail(10)

,BOWLING,O,M,R,W,ECON,0s,4s,6s,WD,NB,Bowling_Team,Match,ScoreID
516,Liam Plunkett,10.0,0,42,3,4.20,36,4,0,0,0,England,New Zealand vs England,ODI # 4192
517,Mark Wood,10.0,1,49,1,4.90,33,3,1,2,0,England,New Zealand vs England,ODI # 4192
518,Adil Rashid,8.0,0,39,0,4.87,15,1,0,0,0,England,New Zealand vs England,ODI # 4192
519,Ben Stokes,3.0,0,20,0,6.66,6,2,0,2,0,England,New Zealand vs England,ODI # 4192
520,Trent Boult,10.0,0,67,0,6.70,31,8,1,2,0,New Zealand,New Zealand vs England,ODI # 4192
521,Matt Henry,10.0,2,40,1,4.00,39,5,0,0,0,New Zealand,New Zealand vs England,ODI # 4192
522,Colin de Grandhomme,10.0,2,25,1,2.50,41,1,0,1,0,New Zealand,New Zealand vs England,ODI # 4192
523,Lockie Ferguson,10.0,0,50,3,5.00,35,5,0,3,0,New Zealand,New Zealand vs England,ODI # 4192
524,James Neesham,7.0,0,43,3,6.14,19,3,1,1,0,New Zealand,New Zealand vs England,ODI # 4192
525,Mitchell Santner,3.0,0,11,0,3.66,8,0,0,1,0,New Zealand,New Zealand vs England,ODI # 4192

In [112]:
df_3=pd.read_csv('player_Details.csv')
df_3.head()

,player,Birth_date,Odi played,role,batting style,Bowling Style,Team,Unnamed: 7
0,Gulbadin Naib (c),16 March 1991 (aged 28),55,All-rounder,Right,Right-arm medium-fast,Afghanistan,NaN
1,Rashid Khan (vc),20 September 1998 (aged 20),59,Bowler,Right,Right-arm leg spin,Afghanistan,NaN
2,Aftab Alam,30 November 1992 (aged 26),24,All-rounder,Right,Right-arm medium-fast,Afghanistan,NaN
3,Asghar Afghan,22 February 1987 (aged 32),102,Batsman,Right,Right-arm off spin,Afghanistan,NaN
4,Dawlat Zadran,19 March 1988 (aged 31),77,Bowler,Right,Right-arm fast,Afghanistan,NaN

In [113]:
df_3.drop(columns=['Unnamed: 7'],inplace=True)

In [115]:
df_3.head(15)

,player,Birth_date,Odi played,role,batting style,Bowling Style,Team
0,Gulbadin Naib (c),16 March 1991 (aged 28),55,All-rounder,Right,Right-arm medium-fast,Afghanistan
1,Rashid Khan (vc),20 September 1998 (aged 20),59,Bowler,Right,Right-arm leg spin,Afghanistan
2,Aftab Alam,30 November 1992 (aged 26),24,All-rounder,Right,Right-arm medium-fast,Afghanistan
3,Asghar Afghan,22 February 1987 (aged 32),102,Batsman,Right,Right-arm off spin,Afghanistan
4,Dawlat Zadran,19 March 1988 (aged 31),77,Bowler,Right,Right-arm fast,Afghanistan
5,Hamid Hassan,1 June 1987 (aged 31),33,Bowler,Right,Right-arm fast,Afghanistan
6,Hashmatullah Shahidi,4 November 1994 (aged 24),31,Batsman,Left,Right-arm off spin,Afghanistan
7,Hazratullah Zazai,23 March 1998 (aged 21),8,Batsman,Left,Left-arm orthodox,Afghanistan
8,Mohammad Nabi,3 March 1985 (aged 34),112,All-rounder,Right,Right-arm off spin,Afghanistan
9,Mohammad Shahzad (wk),31 January 1988 (aged 31),82,Wicket-keeper,Right,—,Afghanistan
10,Mujeeb Ur Rahman,28 March 2001 (aged 18),30,Bowler,Right,Right-arm off spin,Afghanistan
11,Najibullah Zadran,18 February 1993 (aged 26),56,Batsman,Left,Right-arm off spin,Afghanistan
12,Noor Ali Zadran,10 July 1988 (aged 30),48,Batsman,Right,Right-arm medium-fast,Afghanistan
13,Rahmat Shah,16 March 1991 (aged 28),61,Batsman,Right,Right-arm leg spin,Afghanistan
14,Samiullah Shinwari,31 December 1987 (aged 31),81,All-rounder,Right,Right-arm leg spin,Afghanistan

In [116]:
df_3['player']=df_3['player'].apply(lambda x: x.replace('(c)',''))
df_3['player']=df_3['player'].apply(lambda x: x.replace('(vc)',''))
df_3['player']=df_3['player'].apply(lambda x: x.replace('(wk)',''))
df_3.head(15)

,player,Birth_date,Odi played,role,batting style,Bowling Style,Team
0,Gulbadin Naib,16 March 1991 (aged 28),55,All-rounder,Right,Right-arm medium-fast,Afghanistan
1,Rashid Khan,20 September 1998 (aged 20),59,Bowler,Right,Right-arm leg spin,Afghanistan
2,Aftab Alam,30 November 1992 (aged 26),24,All-rounder,Right,Right-arm medium-fast,Afghanistan
3,Asghar Afghan,22 February 1987 (aged 32),102,Batsman,Right,Right-arm off spin,Afghanistan
4,Dawlat Zadran,19 March 1988 (aged 31),77,Bowler,Right,Right-arm fast,Afghanistan
5,Hamid Hassan,1 June 1987 (aged 31),33,Bowler,Right,Right-arm fast,Afghanistan
6,Hashmatullah Shahidi,4 November 1994 (aged 24),31,Batsman,Left,Right-arm off spin,Afghanistan
7,Hazratullah Zazai,23 March 1998 (aged 21),8,Batsman,Left,Left-arm orthodox,Afghanistan
8,Mohammad Nabi,3 March 1985 (aged 34),112,All-rounder,Right,Right-arm off spin,Afghanistan
9,Mohammad Shahzad,31 January 1988 (aged 31),82,Wicket-keeper,Right,—,Afghanistan
10,Mujeeb Ur Rahman,28 March 2001 (aged 18),30,Bowler,Right,Right-arm off spin,Afghanistan
11,Najibullah Zadran,18 February 1993 (aged 26),56,Batsman,Left,Right-arm off spin,Afghanistan
12,Noor Ali Zadran,10 July 1988 (aged 30),48,Batsman,Right,Right-arm medium-fast,Afghanistan
13,Rahmat Shah,16 March 1991 (aged 28),61,Batsman,Right,Right-arm leg spin,Afghanistan
14,Samiullah Shinwari,31 December 1987 (aged 31),81,All-rounder,Right,Right-arm leg spin,Afghanistan

In [119]:
df.to_csv("odi_df.csv", index = False)
df_1.to_csv("odi_bat_summary.csv", index = False)
df_2.to_csv("odi_bowl_fact_summary.csv", index = False)
df_3.to_csv("player_Details.csv", index = False)

### saved all the csv files after performing cleaning and transformation of the Data